"""
PE 44:

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk,
for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised;
what is the value of D?
"""

# first lets generate some pentagonal numbers

pent_list = []

for x in range(1,3001):
    num = int(x*((3*x)-1)/2)
    pent_list.append(num)

#explained in next comment
print(pent_list[-1])
limit = 1499500


answer = 0

for x in pent_list:
    for y in pent_list:

        # This if-statement is based on failed prior attempts, the idea is to never check the same thing twice
        # I am sisyphus, here is my rock *holds out brain*
        if(x<=limit):
            break

        elif((x-y not in pent_list) or (x+y not in pent_list)):
            #I AM SUCH A FUCKING MORON WHY DID I MAKE THIS BREAK
            #YOU HAVE NO IDEA (well maybe you do) HOW MUCH TIME I SPENT ON THIS
            continue

        elif(y>x):
            break

        else:

            if(answer == 0):
                answer = x-y
                print("so far we have " + str(x) + " and " + str(y))
                continue

            elif(x-y < answer):
                answer = x-y
                continue

print(answer)
