'''
PE: 45

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''

#While debugging I thought math.isclose() might be useful
# My IDE doesn't recognize it all, which is concerning because
# why would some functions from math import but not others???
# I have a version of python that SHOULD support it.

import math

#quadratic formula so useful for these methods

def is_pent(num):

    pos = (1 + math.sqrt(1+(24*num)))/6

    if(pos.is_integer()):
        return True

    else:
        return False


def is_hex(num):

    pos = (1 + math.sqrt(1+(8*num)))/4

    if(pos.is_integer()):
        return True

    else:
        return False



triangle_list = []

for x in range(1,100001):
    num = int(x*(x+1)/2)
    triangle_list.append(num)


for x in triangle_list:

    if(x<=40755):
        continue

    elif(not is_pent(x) or not is_hex(x)):
        continue

    else:
        print(x)
